### ISSUE TITLE
WebP support

### ISSUE THREAD

**Issue by oxhey** [tridijs/tridi#270]
I don't know if it's already supported , but It would be great if the viewer could support the webp image format.

This is how normal HTML does it so something similar to this would be good.

```
 <picture>
        <source srcset="images/home_banner_2.webp" type="image/webp">
        <source srcset="images/home_banner_2.jpg" type="image/jpeg">
        <img alt="Fiat 500" src="images/home_banner_2.jpg">
      </picture>
```

**Comment by lwojcik** [comment]
Thanks for the suggestion! No promise on ETA, but I'll explore this.

**Comment by soukicz** [comment]
I haven't tried it yet, but you could probably do that just from app without need for tridi support. You can detect WebP support and just pass different image array. Same goes for retina images.
