### ISSUE TITLE
angular 10 help

### ISSUE THREAD

**Issue by marcof-git** [tridijs/tridi#273]
Hi, i have some problems with angular 10+
I initialized the viewer and the "generate" and "load" events are returned correctly, but it remains "display: none" on the ".tridi-viewer". If I remove the style anyway it doesn't work
```
import * as Tridi from 'tridi';
[ ............. ]
@ViewChild('tridiRotator') tridiRotatorRef: ElementRef<HTMLDivElement>;
ngAfterViewInit() {
this.tridiView = Tridi.create({
      element: this.tridiRotatorRef.nativeElement,
      location: '../assets/product/spin',
      format: 'jpg',
      count: 35,
      onViewerGenerate: function() {
        console.log('Viewer generated');
      },
      onLoad: function() {
        console.log('Tridi loaded');
      }
    });
    this.tridiView.load()
  }
```

**Comment by marcof-git** [comment]
Solved by passing an ID to "element" instead of this.tridiRotatorRef.nativeElement.
```
this.render.setAttribute(this.tridiRotatorRef.nativeElement, 'id', `id-${uuidv4()}`);
...
Tridi.create({
element: `#${this.rotator.nativeElement.id}`,
})
```

**Comment by lwojcik** [comment]
@marcof-git thanks for submitting the issue and the resolution! Sorry I was too slow to respond. :(

No promises, but I'll consider adding support for refs as elements.
